name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./hello-user-app

      - name: Lint with ESLint
        run: npx eslint . --ext .js,.ts,.tsx
        working-directory: ./hello-user-app

      - name: Type-check with TypeScript
        run: npx tsc --noEmit
        working-directory: ./hello-user-app
      
      - name: Run unit tests
        run: npm test
        working-directory: ./hello-user-app

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            hello-user-app/src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Build app
        run: npm run tauri:build
        working-directory: ./hello-user-app

      - name: Upload Windows installer
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-${{ github.run_number }}
          path: |
            ./hello-user-app/src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi
            ./hello-user-app/src-tauri/target/x86_64-pc-windows-msvc/release/bundle/zip/*.zip
